name: 'Run Rake'
runs:
  using: "composite"
  steps:
    - run: |
        echo "{NODE_VERSION}=$(grep 'nodejs' "${PROJECT_DIR}/.tool-versions" | grep -oEi '\d+.\d+.\d+')" >> "$GITHUB_ENV"
    - run: |
        echo "{RUBY_VERSION}=$(grep 'ruby' "${PROJECT_DIR}/.tool-versions" | grep -oEi '\d+.\d+.\d+')" >> "$GITHUB_ENV"
    - run: |
        echo $RUBY_VERSION && echo $NODE_VERSION
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler-cache: true
    - uses: actions/setup-node@v4
      with:
        node-version: 18.16.0
        cache: 'npm'
        cache-dependency-path: 'sub-project/package-lock.json'