name: 'Run Rake'
description: ''

inputs:
  path:
    description: 'path to the project'
    required: true

runs:
  using: "composite"
  steps:
    - name: set node version
      working-directory: ${{ inputs.path }}
      shell: bash
      run: pwd