name: 'Run Rake'
inputs:
  project-path:
    required: true
runs:
  using: "composite"
  steps:
    - name: echo .tools
      shell: bash
      run: |
        cat "${{ inputs.project-path }}/.tool-versions"
    - name: echo ls
      shell: bash
      run: |
        ls -al
    - name: echo version
      shell: bash
      run: |
        ./scripts/tool-version.sh ${{ inputs.project-path }} nodejs
    - name: set node version
      shell: bash
      run: echo "NODE_VERSION=$(./scripts/tool-version.sh ${{ inputs.project-path }} nodejs)" >> "$GITHUB_ENV"
    - name: set ruby version
      shell: bash
      run: |
        echo "RUBY_VERSION=$(./scripts/tool-version.sh ${{ inputs.project-path }} ruby)" >> "$GITHUB_ENV"
    - name: print versions
      shell: bash
      run: |
        echo $NODE_VERSION && echo $RUBY_VERSION
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: $RUBY_VERSION
        bundler-cache: true
    - uses: actions/setup-node@v4
      with:
        node-version: $NODE_VERSION
        cache: 'npm'
        cache-dependency-path: 'sub-project/package-lock.json'