name: 'Run Rake'
inputs:
  project-path:
    required: true
runs:
  using: "composite"
  steps:
    - name: echo .tools
      shell: bash
      run: |
        cat "${{ inputs.project-path }}/.tool-versions"
    - name: echo version
      shell: bash
      run: |
        grep 'nodejs' "${{ inputs.project-path }}/.tool-versions"
    - name: echo node version
      shell: bash
      run: |
        grep 'nodejs' "${{ inputs.project-path }}/.tool-versions" | grep -oEi '\d+.\d+.\d+'
    - name: set node version
      shell: bash
      run: |
        echo "NODE_VERSION=$(grep 'nodejs' "${{ inputs.project-path }}/.tool-versions" | grep -oEi '\d+.\d+.\d+')" >> "$GITHUB_ENV"
    - name: set ruby version
      shell: bash
      run: |
        echo "RUBY_VERSION=$(grep 'ruby' "${{ inputs.project-path }}/.tool-versions" | grep -oEi '\d+.\d+.\d+')" >> "$GITHUB_ENV"
    - name: print versions
      shell: bash
      run: |
        echo $NODE_VERSION && echo $RUBY_VERSION
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: $RUBY_VERSION
        bundler-cache: true
    - uses: actions/setup-node@v4
      with:
        node-version: $NODE_VERSION
        cache: 'npm'
        cache-dependency-path: 'sub-project/package-lock.json'