name: 'Run Rake'
env:
  PROJECT_PATH: 'sub-project'
runs:
  using: "composite"
  steps:
    - name: set node version
      shell: bash
      run: |
        echo "{NODE_VERSION}=$(grep 'nodejs' "$PROJECT_PATH/.tool-versions" | grep -oEi '\d+.\d+.\d+')" >> "$GITHUB_ENV"
    - name: set ruby version
      shell: bash
      run: |
        echo "{RUBY_VERSION}=$(grep 'ruby' "$PROJECT_PATH/.tool-versions" | grep -oEi '\d+.\d+.\d+')" >> "$GITHUB_ENV"
    - name: print versions
      shell: bash
      run: |
        echo $RUBY_VERSION && echo $NODE_VERSION
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler-cache: true
    - uses: actions/setup-node@v4
      with:
        node-version: 18.16.0
        cache: 'npm'
        cache-dependency-path: 'sub-project/package-lock.json'