name: Project Checks

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: run
        shell: bash
        run: echo "lint"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run
        shell: bash
        run: echo "test"
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: run
        shell: bash
        run: echo "checks"