name: Project Main

on:
  push:
    branches:
      - main

jobs:
  development-1:
    runs-on: ubuntu-latest
    steps:
      - name: run
        shell: bash
        run: mkdir -p artifacts/some-service && touch artifacts/some-service/Dockerfile
      - uses: actions/upload-artifact@v4
        with:
          name: service
          path: artifacts/some-service

  staging-1:
    needs: [development-1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: service
          path: artifacts/some-service
      - name: run
        shell: bash
        run: ls -l && ls -l artifacts && ls -l artifacts/some-service
