on:
  push:
    branches:
      - main

jobs:
  checks:
    uses: ./.github/workflows/project-checks.yml

  deploy:
    needs: [checks]
    runs-on: ubuntu-latest
    steps:
      - name: run
        shell: bash
        run: echo "deploy"