name: Reviews Admin Workflow
on:
  push:
    paths:
      - 'sub-project/**'

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./sub-project
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
      - uses: actions/setup-node@v4
        with:
          node-version: 18.16.0
          cache: 'npm'
      - name: run tests
        run:  go app:test
